### ISSUE TITLE
Python 3.6 issue with dict_keys

### ISSUE THREAD

**Issue by froger88** [nadirizr/json-logic-py#4]
```
>>> from json_logic import jsonLogic
>>> jsonLogic( { "==" : [1, 1] } )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda/lib/python3.6/site-packages/json_logic/__init__.py", line 13, in jsonLogic
    op = tests.keys()[0]
TypeError: 'dict_keys' object does not support indexing
```

**Comment by froger88** [comment]
After removing 0.6.3 version by pip uninstall, and instalation newest from repository, problem is solved

**Comment by zohabAli** [comment]
pip install git+https://github.com/qubitdigital/json-logic-py.git

worked for me

**Comment by YaraslauZhylko** [comment]
You can now also use `pip install json-logic-qubit`
