### ISSUE TITLE
am getting issue 'dict_keys' object does not support indexing

### ISSUE THREAD

**Issue by suvinks** [nadirizr/json-logic-py#8]

**Comment by suvinks** [comment]
I just pip installed json logic and tried running the stock examples listed in github and got this error

**Comment by suvinks** [comment]
>>> jsonLogic( { "==" : [1, 1] } )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XXXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\json_logic\__init__.py", line 13, in jsonLogic
    op = tests.keys()[0]
TypeError: 'dict_keys' object does not support indexing

**Comment by YaraslauZhylko** [comment]
This issue is fixed in my Pull Request #7. Aalong with many other code/compatibility issues.

But as this repository does not seem to be maintained anymore I'd suggest using my fork [YaraslauZhylko/json-logic-py](https://github.com/YaraslauZhylko/json-logic-py) or a fork by @qubitdigital [qubitdigital/json-logic-py](https://github.com/qubitdigital/json-logic-py).

The latter one has some more issues addressed and will hopefully soon have a maintained PyPI package.

**Comment by suvinks** [comment]
Thank you. I tried pip install json-logic-qubit but it it gave me error 
Collecting json-logic-qubit
  Could not find a version that satisfies the requirement json-logic-qubit (from versions: )
No matching distribution found for json-logic-qubit

Does it only work for Python 2.7? am using 3.6

**Comment by suvinks** [comment]
got it to work 
pip install git+https://github.com/qubitdigital/json-logic-py.git

Thank you

**Comment by Mochnant** [comment]
I also noticed that the pip installer for qubit fork doesn't seem to work on 3.6.5.

I get the same error as the reporter on 0.6.3 with the main repo.  However, there appears to be a newer version, 0.7.0a0 that does allow the first example to work.

**Comment by YaraslauZhylko** [comment]
@Mochnant

This repo does not seem to be maintained any more.

I would have advised you to create a separate Issue on @qubitdigital fork page [qubitdigital/json-logic-py](https://github.com/qubitdigital/json-logic-py) (as they have the most advanced code at the moment), but cannot find the "Issues" tab there...

Maybe try contacting @mmniaziqb (the actual developer behind that fork) directly?

**Comment by mmniaziqb** [comment]
Hi guys, I originally made that fork for internal use in company, but it seems more people are interested in it. I will try to fix above issues in coming week (and few things pointed by @YaraslauZhylko).

And thanks @YaraslauZhylko for pointing out bunch of stuff, I will get in touch with who ever has complete access to github organization in our team to fix the "issues tab missing".

**Comment by Mochnant** [comment]
Thanks, @mmniaziqb and @YaraslauZhylko!

**Comment by mmniaziqb** [comment]
I have uploaded latest version with this fixed on pypi (repo: https://github.com/QubitProducts/json-logic-py)

`pip install json-logic-qubit`
